

export const metadata = {
  title: 'EduTask',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
 

  return (

        <html lang="en">
          <body style={{
            background: 'linear-gradient(to bottom right, #8338EC, #C87DF5)',
          }}>
            {children}
          </body>
        </html>
  );
}
