import Navigation from "../Components/Navigation";
import { TaskProvider } from "../Context/TaskContext";
import "./globals.css";

export const metadata = {
  title: "EduTask",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TaskProvider>
        <Navigation />
        {children}
        </TaskProvider>
      </body>
    </html>
  );
}
